### ISSUE TITLE
Can't start to contribute based on the Readme 

### ISSUE THREAD

**Issue by spiii** [weg-li/weg-li#753]
I'd like to start supporting this project. I have a lot of experience in software development, but I've never worked with Ruby on Rails before. But copilot makes you fit for action just like that. Nevertheless, I've been using weg.li for a long time and would be happy to contribute my user experience to its further development. My issue is that I've struggled with the "How to Contribute" description in the README file. I get many errors related to versions and some specific ruby/weg.li project stuff. The Docker Compose file isn't working either. (@levino maybe you can continue the pr for the #695) After several hours and attempts, I'm feeling pretty desperate and fairly certain that I won't be able to get this project running locally on my own. I'm working on the Windows platform with WSL2.

Would be great if the "How to Contribute" part could be fixed / exactly specified so that I could  start to contribute. Many thanks in advance.

**Comment by levino** [comment]
Whatever. It is all public. People can make up their own minds. I also do not get why you feel treated unjust. I mean it is already a value to open source code for transparency reasons.

**Comment by phoet** [comment]
I would really appreciat if you stopped assuming things

> I also do not get why you feel treated unjust.

You do not know how i feel about your comments.

You also do not know the reasons for why this is open-source.

STOP ASSUMING THINGS

**Comment by levino** [comment]
You can publish all communication you had with me under the condition that you publish it all, including your messages.

I assume as much as I want but I will refrain from sharing my assumptions with you in the future to respect... whatever it is... I am very afraid to make an assumption here...

**Comment by phoet** [comment]
@spiii i made some slight adjustments to the existing docker-compose setup and it runs for me now. see https://github.com/weg-li/weg-li?tab=readme-ov-file#docker-setup

**Comment by spiii** [comment]
Thanks for that I'll check it.
Sorry about your differences guys.
I would say PR is always such a thing.
Maybe you will find some way in the feature.
This project is worth it.
Thanks one more time.

**Comment by phoet** [comment]
did it work?

**Comment by spiii** [comment]
Hey @phoet sorry for not responding for so long. It didn't work unfortunately.I tried to fix it and lost  focus. I'll provide some error reports soon.

**Comment by spiii** [comment]
> Hey @phoet sorry for not responding for so long. It didn't work unfortunately.I tried to fix it and lost focus. I'll provide some error reports soon.

I see some problem with the  `exec ./entrypoints/docker-entrypoint.sh: no such file or directory`
and some other problem with the version of the postgress
`postgres-1  | 2024-05-15 04:56:12.974 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 16, which is not compatible with this version 12.19.
postgres-1 exited with code 1`
see more details on the bottom


powershell on windows:
```
docker-compose up
[+] Building 0.0s (0/0)  docker:default
[+] Building 160.4s (8/13)                                                                                                                                                                      docker:default
 => [app internal] load build definition from Dockerfile                                                                                                                                                  0.1s
 => => transferring dockerfile: 688B                                                                                                                                                                      0.1s 
 => [app internal] load metadata for docker.io/library/ruby:3.2.4-alpine                                                                                                                                 10.0s
 => [app internal] load .dockerignore                                                                                                                                                                     0.1s
 => => transferring context: 237B                                                                                                                                                                         0.0s 
 => [app internal] load build context                                                                                                                                                                     0.3s
 => => transferring context: 42.17kB                                                                                                                                                                      0.3s 
 => [app 1/9] FROM docker.io/library/ruby:3.2.4-alpine@sha256:1336f1998baf42fd295578b47be55cd68b5d6c8eae231d058713529621e12071                                                          [+] Building 160.6s (8/13)                                                                                                                                                                      docker:defaultUN apk add --update --no-cache   gcompat   alpine-sdk   imagemagick   nodejs   postgresql-client   postgresql-dev   tzdata   yarn                                 
 => [app internal] load build definition from Dockerfile                                                                                                                                                  0.1s
 => => transferring dockerfile: 688B                                                                                                                                                                      0.1s
 => [app internal] load metadata for docker.io/library/ruby:3.2.4-alpine                                                                                                                                 10.0s
 => [app internal] load .dockerignore                                                                                                                                                                     0.1s
 => => transferring context: 237B                                                                                                                                                                         0.0s
 => [app internal] load build context                                                                                                                                                   [+] Building 160.7s (8/13)                                                                                                                                                                      docker:defaultntext: 42.17kB                                                                                                                                                    
 => [app internal] load build definition from Dockerfile                                                                                                                                                  0.1sker.io/library/ruby:3.2.4-alpine@sha256:1336f1998baf42fd295578b47be55cd68b5d6c8eae231d058713529621e12071                                                          
 => => transferring dockerfile: 688B                                                                                                                                                                      0.1sUN apk add --update --no-cache   gcompat   alpine-sdk   imagemagick   nodejs   postgresql-client   postgresql-dev   tzdata   yarn                                 
 => [app internal] load metadata for docker.io/library/ruby:3.2.4-alpine                                                                                                                                 10.0sORKDIR /app                                                                                                                                                       
 => [app internal] load .dockerignore                                                                                                                                                                     0.1sOPY Gemfile Gemfile.lock ./                                                                                                                                       
 => => transferring context: 237B                                                                                                                                                                         0.0sle check || bundle install                                                                                                                                        
 => [app internal] load build context                                                                                                                                                                     0.3sack 1.0.0
 => => transferring context: 42.17kB                                                                                                                                                                      0.3stivesupport 7.1.3.2
 => [app 1/9] FROM docker.io/library/ruby:3.2.4-alpine@sha256:1336f1998baf42fd295578b47be55cd68b5d6c8eae231d058713529621e12071                                                                            0.0snk 1.8.0
 => CACHED [app 2/9] RUN apk add --update --no-cache   gcompat   alpine-sdk   imagemagick   nodejs   postgresql-client   postgresql-dev   tzdata   yarn                                 [+] Building 160.9s (8/13)                                                                                                                                                                      docker:defaultORKDIR /app                                                                                                                                                       
 => [app internal] load build definition from Dockerfile                                                                                                                                                  0.1sOPY Gemfile Gemfile.lock ./                                                                                                                                       
 => => transferring dockerfile: 688B                                                                                                                                                                      0.1sle check || bundle install                                                                                                                                        
 => [app internal] load metadata for docker.io/library/ruby:3.2.4-alpine                                                                                                                                 10.0sack 1.0.0                                                                                                                                                         
 => [app internal] load .dockerignore                                                                                                                                                                     0.1si_xml 0.7.1                                                                                                                                                       
 => => transferring context: 237B                                                                                                                                                                         0.0stivesupport 7.1.3.2                                                                                                                                               
 => [app internal] load build context                                                                                                                                                                     0.3slti_xml 0.7.1                                                                                                                                                     
 => => transferring context: 42.17kB                                                                                                                                                                      0.3snk 1.8.0                                                                                                                                                          
 => [app 1/9] FROM docker.io/library/ruby:3.2.4-alpine@sha256:1336f1998baf42fd295578b47be55cd68b5d6c8eae231d058713529621e12071                                                                            0.0sfunk 1.8.0                                                                                                                                                        
 => CACHED [app 2/9] RUN apk add --update --no-cache   gcompat   alpine-sdk   imagemagick   nodejs   postgresql-client   postgresql-dev   tzdata   yarn                                 [+] Building 161.0s (8/13)                                                                                                                                                                      docker:defaultORKDIR /app                                                                                                                                                       
 => [app internal] load build definition from Dockerfile                                                                                                                                                  0.1sOPY Gemfile Gemfile.lock ./                                                                                                                                       
 => => transferring dockerfile: 688B                                                                                                                                                                      0.1sle check || bundle install                                                                                                                                        
 => [app internal] load metadata for docker.io/library/ruby:3.2.4-alpine                                                                                                                                 10.0sack 1.0.0                                                                                                                                                         
 => [app internal] load .dockerignore                                                                                                                                                                     0.1si_xml 0.7.1                                                                                                                                                       
 => => transferring context: 237B                                                                                                                                                                         0.0stivesupport 7.1.3.2                                                                                                                                               
 => [app internal] load build context                                                                                                                                                                     0.3slti_xml 0.7.1                                                                                                                                                     
 => => transferring context: 42.17kB                                                                                                                                                                      0.3snk 1.8.0                                                                                                                                                          
 => [app 1/9] FROM docker.io/library/ruby:3.2.4-alpine@sha256:1336f1998baf42fd295578b47be55cd68b5d6c8eae231d058713529621e12071                                                                            0.0sfunk 1.8.0                                                                                                                                                        
 => CACHED [app 2/9] RUN apk add --update --no-cache   gcompat   alpine-sdk   imagemagick   nodejs   postgresql-client   postgresql-dev   tzdata   yarn                                 [+] Building 682.3s (14/14) FINISHED                                                                                                                                     docker:default
 => [app internal] load build definition from Dockerfile                                                                                                                           0.1s 
 => => transferring dockerfile: 688B                                                                                                                                               0.1s
 => [app internal] load metadata for docker.io/library/ruby:3.2.4-alpine                                                                                                          10.0s 
 => [app internal] load .dockerignore                                                                                                                                              0.1s
 => => transferring context: 237B                                                                                                                                                  0.0s 
 => [app internal] load build context                                                                                                                                              0.3s
 => => transferring context: 42.17kB                                                                                                                                               0.3s 
 => [app 1/9] FROM docker.io/library/ruby:3.2.4-alpine@sha256:1336f1998baf42fd295578b47be55cd68b5d6c8eae231d058713529621e12071                                                     0.0s
 => CACHED [app 2/9] RUN apk add --update --no-cache   gcompat   alpine-sdk   imagemagick   nodejs   postgresql-client   postgresql-dev   tzdata   yarn                            0.0s 
 => CACHED [app 3/9] WORKDIR /app                                                                                                                                                  0.0s
 => CACHED [app 4/9] COPY Gemfile Gemfile.lock ./                                                                                                                                  0.0s 
 => [app 5/9] RUN bundle check || bundle install                                                                                                                                 418.9s
 => [app 6/9] COPY package.json yarn.lock ./                                                                                                                                       0.1s
 => [app 7/9] RUN yarn install --check-files                                                                                                                                      93.9s
 => [app 8/9] COPY . ./                                                                                                                                                            0.9s
 => [app 9/9] RUN NODE_OPTIONS=--openssl-legacy-provider RAILS_ENV=production SECRET_KEY_BASE=6254271520a1865fabd321490051fb35e5ab0591ee99dd1f8e0f5dc1719e45cbf328d43bfd47e5829  127.9s
 => [app] exporting to image                                                                                                                                                      29.4s
 => => exporting layers                                                                                                                                                           29.4s
 => => writing image sha256:8760440eec3b669eed37a2a096ad4bf70c8eb5fa8b4a312e672ba6b0289f9a0b                                                                                       0.0s
 => => naming to docker.io/library/weg-li-app                                                                                                                                      0.0s
[+] Running 4/4
 ✔ Network weg-li_default       Created                                                                                                                                            0.3s 
 ✔ Container weg-li-redis-1     Created                                                                                                                                            1.4s 
 ✔ Container weg-li-postgres-1  Created                                                                                                                                            1.3s 
 ✔ Container weg-li-app-1       Created                                                                                                                                            0.5s 
Attaching to app-1, postgres-1, redis-1
postgres-1  | 
postgres-1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres-1  |
redis-1     | 1:C 15 May 2024 04:56:12.792 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis-1     | 1:C 15 May 2024 04:56:12.792 * Redis version=7.2.4, bits=64, commit=00000000, modified=0, pid=1, just started
redis-1     | 1:C 15 May 2024 04:56:12.792 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf        
redis-1     | 1:M 15 May 2024 04:56:12.793 * monotonic clock: POSIX clock_gettime
redis-1     | 1:M 15 May 2024 04:56:12.798 * Running mode=standalone, port=6379.
redis-1     | 1:M 15 May 2024 04:56:12.800 * Server initialized
redis-1     | 1:M 15 May 2024 04:56:12.804 * Ready to accept connections tcp
postgres-1  | 2024-05-15 04:56:12.974 UTC [1] FATAL:  database files are incompatible with server
postgres-1  | 2024-05-15 04:56:12.974 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 16, which is not compatible with this version 12.19.
postgres-1 exited with code 1
app-1       | exec ./entrypoints/docker-entrypoint.sh: no such file or directory
app-1 exited with code 1
```

linux (wls)

```
sudo docker-compose up
[+] Running 4/4
 ✔ Network weg-li_default       Created                                                                                                                                                0.1s
 ✔ Container weg-li-redis-1     Created                                                                                                                                                0.5s
 ✔ Container weg-li-postgres-1  Created                                                                                                                                                0.5s
 ✔ Container weg-li-app-1       Created                                                                                                                                                0.2s
Attaching to app-1, postgres-1, redis-1
postgres-1  |
postgres-1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres-1  |
redis-1     | 1:C 15 May 2024 04:57:24.271 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis-1     | 1:C 15 May 2024 04:57:24.271 * Redis version=7.2.4, bits=64, commit=00000000, modified=0, pid=1, just started
redis-1     | 1:C 15 May 2024 04:57:24.271 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis-1     | 1:M 15 May 2024 04:57:24.273 * monotonic clock: POSIX clock_gettime
redis-1     | 1:M 15 May 2024 04:57:24.278 * Running mode=standalone, port=6379.
redis-1     | 1:M 15 May 2024 04:57:24.279 * Server initialized
redis-1     | 1:M 15 May 2024 04:57:24.285 * Ready to accept connections tcp
postgres-1  | 2024-05-15 04:57:24.389 UTC [1] FATAL:  database files are incompatible with server
postgres-1  | 2024-05-15 04:57:24.389 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 16, which is not compatible with this version 12.19.
postgres-1 exited with code 1
app-1       | The i18n gem is not available. Please add it to your Gemfile and run bundle install
app-1       | /usr/local/bundle/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require': cannot load such file -- i18n (LoadError)
app-1       |   from /usr/local/bundle/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
app-1       |   from /usr/local/bundle/gems/activesupport-7.1.3.2/lib/active_support/i18n.rb:7:in `<main>'
app-1       |   from /usr/local/bundle/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
app-1       |   from /usr/local/bundle/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
app-1       |   from /usr/local/bundle/gems/activesupport-7.1.3.2/lib/active_support/inflector/inflections.rb:4:in `<main>'
app-1       |   from /usr/local/bundle/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
app-1       |   from /usr/local/bundle/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
app-1       |   from /usr/local/bundle/gems/activesupport-7.1.3.2/lib/active_support/inflections.rb:3:in `<main>'
app-1       |   from /usr/local/bundle/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
app-1       |   from /usr/local/bundle/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
app-1       |   from /usr/local/bundle/gems/activesupport-7.1.3.2/lib/active_support/inflector/methods.rb:3:in `<main>'
app-1       |   from /usr/local/bundle/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
app-1       |   from /usr/local/bundle/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
app-1       |   from /usr/local/bundle/gems/activesupport-7.1.3.2/lib/active_support/dependencies/autoload.rb:3:in `<main>'
app-1       |   from /usr/local/bundle/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
app-1       |   from /usr/local/bundle/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
app-1       |   from /usr/local/bundle/gems/activesupport-7.1.3.2/lib/active_support.rb:27:in `<main>'
app-1       |   from /usr/local/bundle/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
app-1       |   from /usr/local/bundle/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
app-1       |   from /usr/local/bundle/gems/railties-7.1.3.2/lib/rails/command.rb:3:in `<main>'
app-1       |   from /usr/local/bundle/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
app-1       |   from /usr/local/bundle/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
app-1       |   from /usr/local/bundle/gems/railties-7.1.3.2/lib/rails/commands.rb:3:in `<main>'
app-1       |   from /usr/local/bundle/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
app-1       |   from /usr/local/bundle/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
app-1       |   from bin/rails:4:in `<main>'
app-1 exited with code 1
```

**Comment by phoet** [comment]
I'm not much of a help here, since I dont have access to a Windows computer. I can only tell you that it works on mac and linux 🤷

**Comment by spiii** [comment]
I was able to create development environment in wsl on windows.
The problem was as always in front of the monitor.
